require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const User = require('./models/User');
const Product = require('./models/Product');
const CowShelter = require('./models/CowShelter');
const Farmland = require('./models/Farmland');
const Marketplace = require('./models/Marketplace');

async function seed() {
  await mongoose.connect(process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/agrilink');
  console.log('Connected to MongoDB for seeding...');

  // Clean existing collections
  await Promise.all([
    User.deleteMany({}),
    Product.deleteMany({}),
    CowShelter.deleteMany({}),
    Farmland.deleteMany({}),
    Marketplace.deleteMany({}),
  ]);
  console.log('Cleared existing data.');

  const passwordHash = await bcrypt.hash('password123', 10);

  // 1. Create Farmers and Demo Buyer
  const farmersData = [
    { name: 'Murugan K.', email: 'murugan@agritech.com', phone: '+91 94432 10981', place: 'Salem', coords: [78.146, 11.664] },
    { name: 'Selvi R.', email: 'selvi@agritech.com', phone: '+91 98421 88720', place: 'Erode', coords: [77.727, 11.341] },
    { name: 'Kumaravel S.', email: 'kumaravel@agritech.com', phone: '+91 97883 45129', place: 'Theni', coords: [77.476, 10.010] },
    { name: 'Karthik P.', email: 'karthik@agritech.com', phone: '+91 94872 33100', place: 'Ooty', coords: [76.693, 11.410] },
    { name: 'Anitha M.', email: 'anitha@agritech.com', phone: '+91 99441 66205', place: 'Coimbatore', coords: [76.955, 11.016] },
    { name: 'Ramanathan T.', email: 'ramanathan@agritech.com', phone: '+91 98430 77123', place: 'Madurai', coords: [78.119, 9.925] },
  ];

  const createdFarmers = [];
  for (const f of farmersData) {
    const user = await User.create({
      name: f.name,
      email: f.email,
      password: passwordHash,
      phone: f.phone,
      role: 'farmer',
      verified: true,
      location: { type: 'Point', coordinates: f.coords },
    });
    createdFarmers.push({ ...user.toObject(), place: f.place });
  }

  // Demo Buyer
  await User.create({
    name: 'Priya Sundaram',
    email: 'buyer@agritech.com',
    password: passwordHash,
    phone: '+91 98765 43210',
    role: 'buyer',
    verified: true,
    location: { type: 'Point', coordinates: [78.146, 11.664] },
  });

  console.log(`Created ${createdFarmers.length} farmers and 1 demo buyer.`);

  // 2. Create Rich Products with Realistic Images and Researched Health Benefits
  const productsData = [
    // --- VEGETABLES ---
    {
      farmerIndex: 0,
      name: 'Salem Country Tomatoes (Nattu Thakkali)',
      price: 32,
      quantity: 220,
      unit: 'kg',
      category: 'vegetable',
      place: 'Salem, Tamil Nadu',
      discount: 10,
      healthBenefits: ['skin', 'immunity'],
      healthNote: 'High in Lycopene antioxidant which boosts skin collagen and defends against UV damage.',
      harvestTime: 'Harvested 3 hrs ago',
      rating: 4.9,
      isJuiceSuitable: false,
      image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 3,
      name: 'Ooty Mountain Crisp Carrots',
      price: 48,
      quantity: 160,
      unit: 'kg',
      category: 'vegetable',
      place: 'Ooty, Nilgiris',
      discount: 15,
      healthBenefits: ['hair', 'skin'],
      healthNote: 'Rich in Beta-carotene & Vitamin A which stimulates scalp sebum and fuels hair growth.',
      harvestTime: 'Harvested early morning',
      rating: 4.9,
      isJuiceSuitable: true,
      juicePrice: 32,
      image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 4,
      name: 'Pollachi Red Organic Beetroot',
      price: 42,
      quantity: 140,
      unit: 'kg',
      category: 'vegetable',
      place: 'Pollachi, Coimbatore',
      discount: 5,
      healthBenefits: ['skin', 'digestion'],
      healthNote: 'Dietary nitrates and betalains purify blood, imparting a natural rosy skin glow and aiding gut mobility.',
      harvestTime: 'Fresh harvest',
      rating: 4.8,
      isJuiceSuitable: true,
      juicePrice: 28,
      image: 'https://images.unsplash.com/photo-1593105544559-ecb03bf76f82?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 0,
      name: 'Sweet Potatoes (Sarkaravalli Kizhangu)',
      price: 38,
      quantity: 190,
      unit: 'kg',
      category: 'vegetable',
      place: 'Salem Outer',
      discount: 0,
      healthBenefits: ['hair', 'digestion'],
      healthNote: 'Packed with Biotin and slow-digesting resistant starch that strengthens keratin and feeds healthy gut flora.',
      harvestTime: 'Farm fresh today',
      rating: 4.7,
      isJuiceSuitable: false,
      image: 'https://images.unsplash.com/photo-1596097635121-14b63b7a0c19?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 2,
      name: 'Tender Bottle Gourd (Sorakkai)',
      price: 26,
      quantity: 110,
      unit: 'kg',
      category: 'vegetable',
      place: 'Cumbum Valley, Theni',
      discount: 0,
      healthBenefits: ['digestion', 'immunity'],
      healthNote: '92% pure alkaline water content, speeds up metabolic digestion and neutralizes stomach acidity.',
      harvestTime: 'Harvested 4 hrs ago',
      rating: 4.8,
      isJuiceSuitable: true,
      juicePrice: 18,
      image: 'https://images.unsplash.com/photo-1597362925123-77861d3fbac7?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 1,
      name: 'Crisp Country Cucumber (Vellarikkai)',
      price: 28,
      quantity: 180,
      unit: 'kg',
      category: 'vegetable',
      place: 'Erode Green Farms',
      discount: 10,
      healthBenefits: ['skin', 'digestion'],
      healthNote: 'Contains mineral Silica for skin tissue repair and cucumber enzymes for effortless gut digestion.',
      harvestTime: 'Harvested this morning',
      rating: 4.8,
      isJuiceSuitable: true,
      juicePrice: 19,
      image: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 3,
      name: 'Shimla Green Capsicum / Bell Pepper',
      price: 55,
      quantity: 90,
      unit: 'kg',
      category: 'vegetable',
      place: 'Nilgiris Hills',
      discount: 8,
      healthBenefits: ['skin', 'immunity'],
      healthNote: 'Contains more Vitamin C than oranges, combating skin dullness and bolstering white blood cell defense.',
      harvestTime: 'Picked today',
      rating: 4.9,
      isJuiceSuitable: false,
      image: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 2,
      name: 'Fresh Ginger Root (Nattu Inji)',
      price: 110,
      quantity: 85,
      unit: 'kg',
      category: 'vegetable',
      place: 'Theni Foothills',
      discount: 12,
      healthBenefits: ['immunity', 'digestion'],
      healthNote: 'Potent Gingerol compound reduces nausea, dissolves gut gas, and destroys pathogen microbes.',
      harvestTime: 'Freshly dug rhizomes',
      rating: 5.0,
      isJuiceSuitable: true,
      juicePrice: 85,
      image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 3,
      name: 'Hill Garlic Bulbs (Malai Poondu)',
      price: 160,
      quantity: 70,
      unit: 'kg',
      category: 'vegetable',
      place: 'Kodaikanal Valley',
      discount: 5,
      healthBenefits: ['immunity', 'hair'],
      healthNote: 'Concentrated Allicin antibacterial power stimulates hair root microcirculation and guards immunity.',
      harvestTime: 'Cured Hill Harvest',
      rating: 4.9,
      isJuiceSuitable: false,
      image: 'https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 3,
      name: 'Fresh Green Broccoli Crowns',
      price: 65,
      quantity: 95,
      unit: 'kg',
      category: 'vegetable',
      place: 'Ooty Terrace Farm',
      discount: 10,
      healthBenefits: ['immunity', 'skin'],
      healthNote: 'Packed with Sulforaphane, Zinc, and Vitamin E to detoxify epidermal cells and protect immunity.',
      harvestTime: 'Harvested at dawn',
      rating: 4.9,
      isJuiceSuitable: false,
      image: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 0,
      name: 'Nashik Red Onions (Vengayam)',
      price: 36,
      quantity: 350,
      unit: 'kg',
      category: 'vegetable',
      place: 'Salem Mandi Direct',
      discount: 0,
      healthBenefits: ['hair', 'immunity'],
      healthNote: 'Rich in dietary sulfur and Quercetin, clinically proven to prevent hair thinning and regrow follicles.',
      harvestTime: 'Sun dried batch',
      rating: 4.8,
      isJuiceSuitable: false,
      image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=800&auto=format&fit=crop&q=80',
    },

    // --- FRUITS ---
    {
      farmerIndex: 2,
      name: 'Red Lady Sweet Ripe Papaya',
      price: 38,
      quantity: 240,
      unit: 'kg',
      category: 'fruit',
      place: 'Theni Valley',
      discount: 15,
      healthBenefits: ['skin', 'digestion'],
      healthNote: 'Contains natural Papain proteolytic enzymes for instant protein breakdown and luminous skin cell turnover.',
      harvestTime: 'Tree-ripened',
      rating: 4.9,
      isJuiceSuitable: true,
      juicePrice: 22,
      image: 'https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 2,
      name: 'Theni Nendran / Robusta Banana',
      price: 45,
      quantity: 310,
      unit: 'kg',
      category: 'fruit',
      place: 'Theni Agro Belt',
      discount: 10,
      healthBenefits: ['digestion', 'hair'],
      healthNote: 'High prebiotic fructooligosaccharides normalize bowel transit, while Potassium feeds hair thickness.',
      harvestTime: 'Harvested fresh cluster',
      rating: 4.8,
      isJuiceSuitable: true,
      juicePrice: 28,
      image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 0,
      name: 'Nagpur Sweet Juicy Oranges',
      price: 62,
      quantity: 190,
      unit: 'kg',
      category: 'fruit',
      place: 'Salem Orchard',
      discount: 12,
      healthBenefits: ['skin', 'immunity'],
      healthNote: 'Bursting with active Vitamin C and bioflavonoids to clear blemishes and supercharge cellular immunity.',
      harvestTime: 'Farm picked today',
      rating: 4.9,
      isJuiceSuitable: true,
      juicePrice: 38,
      image: 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 2,
      name: 'Vazhakulam Giant Sweet Pineapple',
      price: 50,
      quantity: 150,
      unit: 'kg',
      category: 'fruit',
      place: 'Cumbum Valley, Theni',
      discount: 10,
      healthBenefits: ['digestion', 'immunity'],
      healthNote: 'Famous for Bromelain enzyme, accelerates sluggish digestion and drastically reduces post-meal bloating.',
      harvestTime: 'Golden ripe picked',
      rating: 4.9,
      isJuiceSuitable: true,
      juicePrice: 32,
      image: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 1,
      name: 'Wild Indian Gooseberry (Amla / Nellikai)',
      price: 55,
      quantity: 130,
      unit: 'kg',
      category: 'fruit',
      place: 'Erode Agro Woods',
      discount: 5,
      healthBenefits: ['hair', 'immunity'],
      healthNote: 'Nature\'s richest Vitamin C source; stops hair fall at root level, prevents premature graying, and protects immune T-cells.',
      harvestTime: 'Wild forest collected',
      rating: 5.0,
      isJuiceSuitable: true,
      juicePrice: 40,
      image: 'https://images.unsplash.com/photo-1589820296156-2454bb8a6ad1?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 4,
      name: 'Allahabad Safeda Sweet Guava',
      price: 46,
      quantity: 175,
      unit: 'kg',
      category: 'fruit',
      place: 'Coimbatore Orchard',
      discount: 8,
      healthBenefits: ['hair', 'immunity'],
      healthNote: 'Packed with 4x more Vitamin C than lemons, boosting scalp collagen synthesis and stopping hair breakage.',
      harvestTime: 'Hand picked today',
      rating: 4.8,
      isJuiceSuitable: true,
      juicePrice: 28,
      image: 'https://images.unsplash.com/photo-1536511135899-73b320d3e5aa?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 5,
      name: 'Arakta Ruby Red Pomegranate',
      price: 120,
      quantity: 140,
      unit: 'kg',
      category: 'fruit',
      place: 'Madurai Orchards',
      discount: 15,
      healthBenefits: ['immunity', 'skin'],
      healthNote: 'Rich in Punicalagin polyphenols that fight free-radical aging and boost immune resistance.',
      harvestTime: 'Tree ripened',
      rating: 4.9,
      isJuiceSuitable: true,
      juicePrice: 75,
      image: 'https://images.unsplash.com/photo-1541344999736-83eca872f242?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 0,
      name: 'Sweet Sun-Ripened Watermelon',
      price: 24,
      quantity: 420,
      unit: 'kg',
      category: 'fruit',
      place: 'Salem River Bed',
      discount: 0,
      healthBenefits: ['skin', 'digestion'],
      healthNote: 'Hydrates skin with Lycopene and Citrulline, promoting clear complexion and fluid digestive transit.',
      harvestTime: 'Harvested yesterday evening',
      rating: 4.8,
      isJuiceSuitable: true,
      juicePrice: 15,
      image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 2,
      name: 'Kagzi Juicy Lemons (Elumichai)',
      price: 60,
      quantity: 100,
      unit: 'kg',
      category: 'fruit',
      place: 'Theni Grove',
      discount: 10,
      healthBenefits: ['immunity', 'digestion'],
      healthNote: 'Stimulates digestive enzymes, flushes toxins, and provides rapid bioavailable Vitamin C.',
      harvestTime: 'Freshly picked',
      rating: 4.8,
      isJuiceSuitable: true,
      juicePrice: 38,
      image: 'https://images.unsplash.com/photo-1590502593747-42a996133562?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 0,
      name: 'Salem Alphonso Sweet Mango',
      price: 95,
      quantity: 120,
      unit: 'kg',
      category: 'fruit',
      place: 'Salem Mango Belt',
      discount: 10,
      healthBenefits: ['skin', 'immunity'],
      healthNote: 'Rich in Vitamin A and Carotenoids for silky skin barrier and fortified immune strength.',
      harvestTime: 'Naturally ripened',
      rating: 5.0,
      isJuiceSuitable: true,
      juicePrice: 58,
      image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=800&auto=format&fit=crop&q=80',
    },

    // --- GREENS (KEERAI) ---
    {
      farmerIndex: 1,
      name: 'Fresh Farm Palak (Spinach Keerai)',
      price: 22,
      quantity: 260,
      unit: 'bunch',
      category: 'greens',
      place: 'Erode River Farms',
      discount: 0,
      healthBenefits: ['hair', 'immunity'],
      healthNote: 'Concentrated Iron, Folate, and Vitamins A/C fuel red blood cell oxygenation to dormant hair roots.',
      harvestTime: 'Harvested 2 hrs ago',
      rating: 4.9,
      isJuiceSuitable: true,
      juicePrice: 15,
      image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 0,
      name: 'Murungai Keerai (Moringa / Drumstick Leaves)',
      price: 20,
      quantity: 300,
      unit: 'bunch',
      category: 'greens',
      place: 'Salem Organic Groves',
      discount: 0,
      healthBenefits: ['immunity', 'hair'],
      healthNote: 'Global superfood with 7x more Vitamin C than oranges and all essential amino acids for keratin rebuild.',
      harvestTime: 'Cut fresh this morning',
      rating: 5.0,
      isJuiceSuitable: false,
      image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 4,
      name: 'Aromatic Curry Leaves (Kariveppilai)',
      price: 18,
      quantity: 340,
      unit: 'bunch',
      category: 'greens',
      place: 'Coimbatore Green Belt',
      discount: 0,
      healthBenefits: ['hair', 'digestion'],
      healthNote: 'Prized herb loaded with Beta-carotene and Amino Acids that stop hair thinning, repair follicles, and stimulate digestive fire.',
      harvestTime: 'Freshly harvested',
      rating: 5.0,
      isJuiceSuitable: false,
      image: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 1,
      name: 'Fresh Aromatic Mint (Pudina Keerai)',
      price: 15,
      quantity: 280,
      unit: 'bunch',
      category: 'greens',
      place: 'Erode Organic Valley',
      discount: 0,
      healthBenefits: ['digestion', 'skin'],
      healthNote: 'Natural Menthol relaxes gastrointestinal smooth muscles, eliminating bloating and clearing oily skin.',
      harvestTime: 'Picked 3 hrs ago',
      rating: 4.9,
      isJuiceSuitable: true,
      juicePrice: 10,
      image: 'https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 0,
      name: 'Crisp Country Coriander (Kothamalli)',
      price: 16,
      quantity: 250,
      unit: 'bunch',
      category: 'greens',
      place: 'Salem Village Green',
      discount: 0,
      healthBenefits: ['digestion', 'skin'],
      healthNote: 'Aids metabolic detox, relieves heavy digestive loads, and clears inflammatory skin breakouts.',
      harvestTime: 'Picked today at 6 AM',
      rating: 4.8,
      isJuiceSuitable: false,
      image: 'https://images.unsplash.com/photo-1589135233689-d5612f00a588?w=800&auto=format&fit=crop&q=80',
    },
    {
      farmerIndex: 2,
      name: 'Organic Methi Leaves (Vendhaya Keerai)',
      price: 20,
      quantity: 180,
      unit: 'bunch',
      category: 'greens',
      place: 'Theni Organic Patch',
      discount: 0,
      healthBenefits: ['hair', 'digestion'],
      healthNote: 'Supplies biological nicotinic acid and proteins that rejuvenate hair roots and maintain healthy gut flora.',
      harvestTime: 'Tender baby greens',
      rating: 4.8,
      isJuiceSuitable: false,
      image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&auto=format&fit=crop&q=80',
    },
  ];

  for (const item of productsData) {
    const farmer = createdFarmers[item.farmerIndex];
    await Product.create({
      farmer: farmer._id,
      name: item.name,
      price: item.price,
      quantity: item.quantity,
      unit: item.unit,
      category: item.category,
      place: item.place,
      discount: item.discount,
      healthBenefits: item.healthBenefits,
      healthNote: item.healthNote,
      harvestTime: item.harvestTime,
      rating: item.rating,
      isJuiceSuitable: item.isJuiceSuitable,
      juicePrice: item.juicePrice || 0,
      isAvailable: true,
      image: item.image,
    });
  }
  console.log(`Created ${productsData.length} products with stock, health research, and realistic photos.`);

  // 3. Create Cow Shelters & Gaushalas
  const sheltersData = [
    {
      name: 'Sri Krishna Desi Gaushala & Gomata Sanctuary',
      place: 'Outer Ring Road, Salem',
      district: 'Salem',
      contactPerson: 'Venkatachalam Shastri',
      phone: '+91 94421 77310',
      image: 'https://images.unsplash.com/photo-1546445317-29f4545e9d53?w=800&auto=format&fit=crop&q=80',
      capacity: '380 Native Gir & Kangeyam Cows',
      cowCount: 380,
      dailyNeedKg: 1500,
      currentStockKg: 420,
      acceptableWaste: ['Vegetable Peels', 'Greens Residue', 'Cabbage Leaves', 'Corn Stalks', 'Paddy Straw'],
      buyRatePerKg: 4.5,
      freePickupMinKg: 80,
      description: 'Dedicated sanctuary for 380 indigenous cows. Daily green waste, vegetable market surplus, and grass feed needed. Free doorstep vehicle pickup for loads above 80 kg.',
      location: { type: 'Point', coordinates: [78.146, 11.664] },
    },
    {
      name: 'Gokulam Vedic Dairy & Cattle Rescue Haven',
      place: 'Thondamuthur Road, Coimbatore',
      district: 'Coimbatore',
      contactPerson: 'Suresh Kumar',
      phone: '+91 98940 12894',
      image: 'https://images.unsplash.com/photo-1596733430284-f7437764b1a9?w=800&auto=format&fit=crop&q=80',
      capacity: '290 Rescued Cows & Calves',
      cowCount: 290,
      dailyNeedKg: 1200,
      currentStockKg: 280,
      acceptableWaste: ['Greens Waste', 'Tomato/Fruit Discards', 'Sweet Potato Vines', 'Sugarcane Tops'],
      buyRatePerKg: 5.0,
      freePickupMinKg: 100,
      description: 'Vedic care facility with high standards of fodder nutrition. We gladly purchase damaged green harvest, excess market greens, and agricultural waste from farmers.',
      location: { type: 'Point', coordinates: [76.955, 11.016] },
    },
    {
      name: 'Kamadhenu Organic Cattle & Bio-Compost Farm',
      place: 'Perundurai Bypass, Erode',
      district: 'Erode',
      contactPerson: 'Balasubramaniam E.',
      phone: '+91 97861 33209',
      image: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800&auto=format&fit=crop&q=80',
      capacity: '420 Native Breed Cattle',
      cowCount: 420,
      dailyNeedKg: 1800,
      currentStockKg: 510,
      acceptableWaste: ['Crop Trimmings', 'Leafy Greens', 'Fruit Pulp', 'Banana Tree Stems', 'Vegetable Surplus'],
      buyRatePerKg: 4.2,
      freePickupMinKg: 60,
      description: 'Large-scale organic sanctuary producing Jeevamrutham and bio-fertilizer. High daily intake of fresh agricultural green trimmings and fruit discards.',
      location: { type: 'Point', coordinates: [77.727, 11.341] },
    },
    {
      name: 'Kongu Heritage Desi Cow Sanctuary',
      place: 'Kangeyam Road, Tiruppur',
      district: 'Tiruppur',
      contactPerson: 'Muthusamy G.',
      phone: '+91 94862 44180',
      image: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=800&auto=format&fit=crop&q=80',
      capacity: '310 Pure Kangeyam Cattle',
      cowCount: 310,
      dailyNeedKg: 1100,
      currentStockKg: 350,
      acceptableWaste: ['Greens Residue', 'Vegetable Cuts', 'Husk', 'Paddy Straw', 'Papaya / Fruit Peels'],
      buyRatePerKg: 4.8,
      freePickupMinKg: 75,
      description: 'Preserving purebred Kangeyam indigenous cattle. Transparent weighing and instant payment for farm waste or donation tax receipts provided.',
      location: { type: 'Point', coordinates: [77.341, 11.108] },
    },
    {
      name: 'Thiruvannamalai Hill Cattle Rescue Sanctuary',
      place: 'Girivalam Path, Thiruvannamalai',
      district: 'Thiruvannamalai',
      contactPerson: 'Narayanan Raman',
      phone: '+91 99420 55102',
      image: 'https://images.unsplash.com/photo-1568644396922-5c3bfae12521?w=800&auto=format&fit=crop&q=80',
      capacity: '250 Holy Cows & Calves',
      cowCount: 250,
      dailyNeedKg: 950,
      currentStockKg: 190,
      acceptableWaste: ['All Green Vegetables', 'Spinach Trimmings', 'Fruit Skins', 'Grass Bundles'],
      buyRatePerKg: 4.0,
      freePickupMinKg: 50,
      description: 'Charitable gaushala feeding 250 gentle cows around the sacred hill. Welcoming daily organic farm residues and greens donations or subsidized purchase.',
      location: { type: 'Point', coordinates: [79.074, 12.225] },
    },
    {
      name: 'Theni Valley Dairy & Cattle Bio-Feed Co-op',
      place: 'Bodinayakanur Road, Theni',
      district: 'Theni',
      contactPerson: 'Kandasamy V.',
      phone: '+91 94438 88912',
      image: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?w=800&auto=format&fit=crop&q=80',
      capacity: '220 Cows',
      cowCount: 220,
      dailyNeedKg: 900,
      currentStockKg: 310,
      acceptableWaste: ['Banana Waste', 'Fruit Peels', 'Vegetable Discards', 'Greens Leaves'],
      buyRatePerKg: 4.5,
      freePickupMinKg: 70,
      description: 'Cumbum valley co-operative taking all banana pseudostem, fruit pulp discards, and unsold leafy greens directly from farmers.',
      location: { type: 'Point', coordinates: [77.476, 10.010] },
    },
  ];

  await CowShelter.insertMany(sheltersData);
  console.log(`Created ${sheltersData.length} Cow Shelters with realistic imagery and feeding metrics.`);

  // 4. Create Farmlands for Contract Farming
  const farmlandsData = [
    {
      title: 'Mettupalayam 5-Acre Fertile Riverland',
      ownerName: 'Thangavel Chettiar',
      phone: '+91 94431 11200',
      place: 'Mettupalayam, Coimbatore',
      district: 'Coimbatore',
      totalAcres: 5.0,
      availableAcres: 3.5,
      soilType: 'Deep Red Loam Soil (pH 6.8)',
      waterSource: 'Bhavani River Canal + 2 Borewells with Drip Lines',
      cropsSuitable: ['Tomatoes', 'Spinach & Greens', 'Papaya', 'Banana'],
      contractType: 'Seasonal 6-Month Buyback Contract',
      ratePerAcre: 42000,
      contractPeriod: '6 to 12 Months',
      image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800&auto=format&fit=crop&q=80',
      description: 'Lush agricultural farmland ready for forward contract farming. Excellent road access, automated drip irrigation, organic compost enriched soil.',
      organicCertified: true,
      location: { type: 'Point', coordinates: [76.955, 11.016] },
    },
    {
      title: 'Yercaud Foothills 4-Acre Mountain Farmland',
      ownerName: 'Palanisamy G.',
      phone: '+91 98422 66315',
      place: 'Foot of Yercaud, Salem',
      district: 'Salem',
      totalAcres: 4.0,
      availableAcres: 4.0,
      soilType: 'Mineral-Rich Hill Loam Soil',
      waterSource: 'Perennial Mountain Stream + Open Well',
      cropsSuitable: ['Carrots', 'Sweet Potato', 'Palak Keerai', 'Bell Peppers'],
      contractType: 'Full Harvest Purchase Agreement',
      ratePerAcre: 38000,
      contractPeriod: '6 Months (Renewable)',
      image: 'https://images.unsplash.com/photo-1523741543316-beb7fc7023d8?w=800&auto=format&fit=crop&q=80',
      description: 'Cool microclimate farmland ideal for high-value root vegetables, exotic greens, and sweet potato contract farming with guaranteed buyback options.',
      organicCertified: true,
      location: { type: 'Point', coordinates: [78.146, 11.664] },
    },
    {
      title: 'Cumbum Valley 6-Acre Rich Farmland',
      ownerName: 'Manickam V.',
      phone: '+91 97893 22105',
      place: 'Cumbum Valley, Theni',
      district: 'Theni',
      totalAcres: 6.0,
      availableAcres: 4.5,
      soilType: 'Alluvial River Basin Soil',
      waterSource: 'Periyar Dam Canal Irrigation (24x7)',
      cropsSuitable: ['Banana', 'Guava', 'Pineapple', 'Bottle Gourd'],
      contractType: 'Commercial Fruit & Veg Contract',
      ratePerAcre: 48000,
      contractPeriod: '1 Year Full Cycle',
      image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&auto=format&fit=crop&q=80',
      description: 'Located in Tamil Nadu\'s most fertile valley. Unlimited water access, high yield history, pre-installed trellis for creepers and fruit orchards.',
      organicCertified: false,
      location: { type: 'Point', coordinates: [77.476, 10.010] },
    },
    {
      title: 'Bhavani River Basin 3.5-Acre Organic Plot',
      ownerName: 'Dhanapal K.',
      phone: '+91 94871 99044',
      place: 'Bhavani, Erode',
      district: 'Erode',
      totalAcres: 3.5,
      availableAcres: 2.0,
      soilType: 'Black Cotton Soil (Moisture Retentive)',
      waterSource: 'River Lift Irrigation + Solar Pump',
      cropsSuitable: ['Turmeric', 'Murungai (Moringa)', 'Curry Leaves', 'Ginger'],
      contractType: 'Organic Forward Buyback Contract',
      ratePerAcre: 36000,
      contractPeriod: '8 Months',
      image: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?w=800&auto=format&fit=crop&q=80',
      description: 'Certified 100% organic plot for 7 years. Ideal for buyers and food processing companies looking for contract organic moringa and medicinal herbs.',
      organicCertified: true,
      location: { type: 'Point', coordinates: [77.727, 11.341] },
    },
    {
      title: 'Hosur Agro-Corridor 8-Acre Greenhouse Farmland',
      ownerName: 'Venkatesan R.',
      phone: '+91 99440 33812',
      place: 'Kelamangalam Road, Hosur',
      district: 'Krishnagiri / Hosur',
      totalAcres: 8.0,
      availableAcres: 5.0,
      soilType: 'Polyhouse Sandy Loam with Coco-Peat Beds',
      waterSource: 'Rainwater Harvesting Lake + Reverse Osmosis Drip',
      cropsSuitable: ['Bell Peppers', 'Broccoli', 'Cucumber', 'Cherry Tomatoes'],
      contractType: 'Precision High-Tech Contract Farming',
      ratePerAcre: 55000,
      contractPeriod: '12 Months',
      image: 'https://images.unsplash.com/photo-1523741543316-beb7fc7023d8?w=800&auto=format&fit=crop&q=80',
      description: 'Modern climate-controlled greenhouses just 40km from Bangalore market. Rapid produce transit, highest grade vegetables for retail and exports.',
      organicCertified: true,
      location: { type: 'Point', coordinates: [77.828, 12.740] },
    },
  ];

  await Farmland.insertMany(farmlandsData);
  console.log(`Created ${farmlandsData.length} Farmlands for contract farming.`);

  // 5. Create Marketplaces, Mandis & Uzhavar Sandhais
  const marketplacesData = [
    {
      name: 'Salem Uzhavar Sandhai (Farmer Direct Market)',
      type: 'uzhavar_sandhai',
      place: 'Suramangalam, Salem',
      district: 'Salem',
      operatingHours: '4:30 AM - 11:30 AM',
      topCommodities: ['Country Tomatoes', 'Palak Keerai', 'Carrots', 'Country Gourds'],
      commissionFee: '0% (Direct Farmer to Consumer, Zero Intermediaries)',
      phone: '+91 427 244 8910',
      image: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&auto=format&fit=crop&q=80',
      dailyArrivalTonnes: 35,
      location: { type: 'Point', coordinates: [78.146, 11.664] },
    },
    {
      name: 'Coimbatore APMC Wholesale Vegetable & Fruit Mandi',
      type: 'apmc_mandi',
      place: 'MTP Road, Coimbatore',
      district: 'Coimbatore',
      operatingHours: '3:00 AM - 1:00 PM',
      topCommodities: ['All Vegetables', 'Oranges', 'Bananas', 'Potatoes & Onions'],
      commissionFee: 'Government Mandi Regulated 2%',
      phone: '+91 422 254 1120',
      image: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=800&auto=format&fit=crop&q=80',
      dailyArrivalTonnes: 120,
      location: { type: 'Point', coordinates: [76.955, 11.016] },
    },
    {
      name: 'Erode Uzhavar Sandhai & Agro Cooperative Center',
      type: 'uzhavar_sandhai',
      place: 'Sampath Nagar, Erode',
      district: 'Erode',
      operatingHours: '5:00 AM - 12:00 PM',
      topCommodities: ['Greens & Keerai Varieties', 'Turmeric', 'Ginger', 'Beetroot'],
      commissionFee: '0% (Direct Farmer Platform with Free Weighing Scales)',
      phone: '+91 424 225 3301',
      image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&auto=format&fit=crop&q=80',
      dailyArrivalTonnes: 28,
      location: { type: 'Point', coordinates: [77.727, 11.341] },
    },
    {
      name: 'Theni Wholesale Banana & Sub-Tropical Fruit Hub',
      type: 'wholesale_hub',
      place: 'Allinagaram, Theni',
      district: 'Theni',
      operatingHours: '4:00 AM - 2:00 PM',
      topCommodities: ['Nendran & Robusta Bananas', 'Papaya', 'Pineapple', 'Watermelon'],
      commissionFee: 'Direct Wholesale Buyer Bidding',
      phone: '+91 4546 252 890',
      image: 'https://images.unsplash.com/photo-1589733955941-5eeaf752f6dd?w=800&auto=format&fit=crop&q=80',
      dailyArrivalTonnes: 85,
      location: { type: 'Point', coordinates: [77.476, 10.010] },
    },
    {
      name: 'Madurai Central Mattuthavani Vegetable Market',
      type: 'apmc_mandi',
      place: 'Mattuthavani, Madurai',
      district: 'Madurai',
      operatingHours: '2:30 AM - 12:00 PM',
      topCommodities: ['Pomegranate', 'Country Tomatoes', 'Drumstick', 'Watermelon'],
      commissionFee: 'APMC Supervised Wholesale',
      phone: '+91 452 258 7741',
      image: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=800&auto=format&fit=crop&q=80',
      dailyArrivalTonnes: 150,
      location: { type: 'Point', coordinates: [78.119, 9.925] },
    },
    {
      name: 'Hosur Fresh Cold-Chain & Juice Procurement Cluster',
      type: 'juice_cluster',
      place: 'SIPCOT Phase 2, Hosur',
      district: 'Krishnagiri / Hosur',
      operatingHours: '6:00 AM - 6:00 PM',
      topCommodities: ['Surplus Fruits for Juicing', 'Pulp Processing', 'Citrus', 'Papaya'],
      commissionFee: 'Direct Juice Shop Wholesale Buyout',
      phone: '+91 4344 278 190',
      image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=800&auto=format&fit=crop&q=80',
      dailyArrivalTonnes: 60,
      location: { type: 'Point', coordinates: [77.828, 12.740] },
    },
  ];

  await Marketplace.insertMany(marketplacesData);
  console.log(`Created ${marketplacesData.length} Marketplaces / Mandis.`);

  console.log('✅ Seeding completed successfully!');
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seeding error:', err);
  process.exit(1);
});
